Cellane/awesome-vapor

PULL_REQUEST_TEMPLATE.md
README.md

- **Project Name**: A few of awesome projects ported from legacy document
- **Project URL**: N/A (multi submission)
- **Project Description**: N/A (multi submission)
- **Why it should be added to `awesome-vapor`**: Because good and helpful work should be promoted

Added good and active projects from legacy document

---

Dangerfile

- **Project Name**: N/A
- **Project URL**: N/A
- **Project Description**: N/A
- **Why it should be added to `awesome-vapor`**: N/A

Added dash and full stop Danger check

---

README.md

- **Project Name**: Lingo Provider
- **Project URL**: https://github.com/vapor-community/Lingo-Provider
- **Project Description**: Vapor provider for Lingo - the Swift localization library.
- **Why it should be added to `awesome-vapor`**: Having a library that helps with localization is extremely important on web.

Added Lingo Provider entry

---

README.md

https://github.com/LiveUI/VaporTestTools
Tools to ease testing in Vapor 3, PR sent on Tanners and Twof's recommendation ...

Adding testing section with VaporTestTools

---

README.md

- **Project Name**: Stripe Provider
- **Project URL**: https://github.com/vapor-community/stripe-provider
- **Project Description**: Stripe Provider for Vapor.
- **Why it should be added to `awesome-vapor`**: Just an entry update

Marked Stripe Provider as Vapor 3 ready

---

README.md

- **Project Name**: Vapor Security Headers
- **Project URL**: https://github.com/brokenhandsio/VaporSecurityHeaders
- **Project Description**: Harden Your Security Headers For Vapor
- **Why it should be added to `awesome-vapor`**: Just an entry update

Marked Vapor Security Headers as Vapor 3 ready

---

README.md

- **Project Name**: SendGrid Provider
- **Project URL**: https://github.com/vapor-community/sendgrid-provider
- **Project Description**: SendGrid-powered mail backend for Vapor
- **Why it should be added to `awesome-vapor`**: SendGrid is a popular alternative to Mailgun.

Added SendGrid Provider entry

---

README.md

Fixed SendGrid Provider typo

---

README.md

- **Project Name**: Swifter
- **Project URL**: https://github.com/LiveUI/Swifter
- **Project Description**: A macOS tool to help you manage your Xcode projects and give you a quick access to DerivedData folder cleaning and management.
- **Why it should be added to `awesome-vapor`**: Old data in DerivedData folder is often a source of confusion and random issues with Vapor projects and this project helps fix that.

Added Swifter

---

README.md

- **Project Name**: Vapor Mailgun Service
- **Project URL**: https://github.com/twof/VaporMailgunService
- **Project Description**: A service to be used with Vapor to send emails.
- **Why it should be added to `awesome-vapor`**: Sending e-mail messages is something that is often needed in web projects.

Added Vapor Mailgun Service entry

---

README.md

- **Project Name**: N/A
- **Project URL**: N/A
- **Project Description**: N/A
- **Why it should be added to `awesome-vapor`**: Just a simple URL fix

Fixed URLs for Docker tutorials

---

README.md

- **Project Name**: CSV Framework
- **Project URL**: https://github.com/skelpo/CSV
- **Project Description**: A simple CSV parser written specifically for and with Vapor.

Added CSV framework and an article on vapor 3.

---

README.md

- **Project Name**: N/A
- **Project URL**: N/A
- **Project Description**: N/A
- **Why it should be added to `awesome-vapor`**: Re-fixing links

Fixed URLs for Docker tutorials; touched up typography

---

README.md

- **Project Name**: Vapor 3 Tutorials
- **Project URL**: https://mihaelamj.github.io/Vapor%20%203%20Tutorial/
- **Project Description**: A huge collection of bite-sized tutorials.

Added Vapor 3 Tutorials entry

---

README.md

- **Project Name**: APNS
- **Project URL**: https://github.com/vapor-community/apns
- **Project Description**: Vapor APNS for iOS

Added APNS entry

---

README.md

- **Project Name**: S3 Storage
- **Project URL**: https://github.com/anthonycastelli/s3-storage
- **Project Description**: Library for simple access to the Amazon S3 service

Added S3 Storage entry

---

README.md

Just an update declaring Vapor 3 compatibility.

Updated SwiftyBeaver Provider entry

---

README.md

- **Project Name**: JWT Middleware
- **Project URL**: https://github.com/skelpo/JWTMiddleware
- **Project Description**: Middleware to Authenticate and Authorize Requests in Vapor

Added JWT Middleware entry

---

README.md

Just a small update to declare Vapor 3 compatibility.

Updated Bugsnag entry

---

README.md

Just a small update declaring Vapor 3 compatibility for several entries.

Updated multiple entries with Vapor 3 compatibility

---

README.md

- **Project Name**: Firebase Provider
- **Project URL**: https://github.com/vapor-community/firebase-provider
- **Project Description**: Vapor Firebase Realtime database provider

Added Firebase Provider entry

---

README.md

- **Project Name**: Ice
- **Project URL**: https://github.com/jakeheis/Ice
- **Project Description**: A developer friendly package manager for Swift; 100% compatible with Swift Package Manager

Replaced Ether with Ice entry

---

README.md

- **Project Name**: Vapor Request Storage
- **Project URL**: https://github.com/skelpo/vapor-request-storage
- **Project Description**: A replacement for `request.storage` which was available in Vapor 1 & 2.

Added Vapor Request Storage entry

---

README.md

- **Project Name**: Vapor reCAPTCHA
- **Project URL**: https://github.com/gotranseo/vapor-recaptcha
- **Project Description**: Validate Google reCAPTCHAs using Vapor 3

Add Vapor Recaptcha

---

README.md

- **Project Name**: Local Storage
- **Project URL**: https://github.com/gperdomor/local-storage
- **Project Description**: Storage driver using local filesystem

Added Local Storage entry

---

README.md

- **Project Name**: N/A
- **Project URL**: N/A
- **Project Description**: N/A
- **Why it should be added to `awesome-vapor`**: N/A

Added article on Docker and Vapor 3

---

README.md

- **Project Name**: Ether
- **Project URL**: https://github.com/Ether-CLI/Ether
- **Project Description**: A Command-Line Interface for the Swift Package Manager

Re-added Ether entry

---

README.md

Removed Travis badge, added table of contents.

Improved Awesome list compliance

---

README.md

… in order to improve chances of being added to the list of Awesome lists.

Added description of Vapor

---

README.md

- **Project Name**: Submissions
- **Project URL**: https://github.com/nodes-vapor/submissions
- **Project Description**: Conveniences for creating forms and validating (form) submissions
- **Why it should be added to `awesome-vapor`**: Looks like an interesting solution to a complex yet frequently encountered problem.

Added Submissions entry

---

README.md

The original S3 library updated and extended for V3

---

README.md

- **Project Name**:
- **Project URL**:
- **Project Description**:

Improved wording on S3 service

---

README.md

- **Project Name**: CSRF
- **Project URL**: https://github.com/vapor-community/CSRF
- **Project Description**: A package to add protection to Vapor against CSRF attacks.
- **Why it should be added to `awesome-vapor`**: Security is always important!

Added CSRF entry

---

README.md

- **Project Name**: FluentQuery
- **Project URL**: https://github.com/MihaelIsaev/FluentQuery
- **Project Description**: Build complex raw SQL queries while still using Swift keypaths.
- **Why it should be added to `awesome-vapor`**: Looks like already quite mature and useful project that immediately gained a lot of traction.

Added FluentQuery entry

---

README.md

- **Project Name**: Guardian
- **Project URL**: https://github.com/Jinxiansen/Guardian
- **Project Description**: Modern rate-limitting middleware.
- **Why it should be added to `awesome-vapor`**: Project looks great and the only other rate-limiting middleware is for Vapor 2.

Added Guardian entry

---

.travis.yml
README.md
bin/filter

This is an attempt to solve issue #45, adding automatically generated filtered lists (one for Vapor 2, one for Vapor 3-related entries) anytime a PR is merged to `master` branch. Unfortunately, due to nature of this repository’s CI setup, success or failure won’t be seen until this PR is actually merged.

First attempt at filtered lists (#45)

---

README.md

Another attempt to solve #45, see commit message for details.

Fix of a fix for filtered lists

---

bin/filter

Another attempt at solving issue #45.

Removed unnecessary vendor/ folder

---

README.md

Hopefully the last PR related to issue #45.

Added links to filtered lists

---

vapor-3.md

- **Project Name**: WKHTMLTOPDF
- **Project URL**: https://github.com/MihaelIsaev/wkhtmltopdf
- **Project Description**: Build pdf file data from Leaf templates and links to web pages through wkhtmltopdf cli.
- **Why it should be added to `awesome-vapor`**: Cause I hope that it's very useful lib 🙂 and I believe that it will take more than 15 stars on GitHub ^_^

Added WKHTMLTOPDF entry

---

README.md

- **Project Name**: Google Cloud Provider
- **Project URL**: https://github.com/vapor-community/google-cloud-provider
- **Project Description**: Interact with Google Cloud Platform APIs from your Vapor project
- **Why it should be added to `awesome-vapor`**: GCP is one of the three large cloud providers, so being able to interact with the APIs can be important.

Added Google Cloud Provider entry

---

README.md

- **Project Name**: VaporExt
- **Project URL**: https://github.com/vapor-community/vapor-ext
- **Project Description**: A collection of Swift extensions for wide range of Vapor data types and classes
- **Why it should be added to `awesome-vapor`**: This library is simply awesome, especially for its async extensions. Makes the code so much more readable.

Added VaporExt entry

---

README.md

there is more but not happy with the readme yet

Some forgotten useful libs

---

README.md

- **Project Name**: SimpleFileLogger
- **Project URL**: https://github.com/hallee/vapor-simple-file-logger
- **Project Description**: A simple Vapor `Logger` provider for outputting server logs to log files.
- **Why it should be added to `awesome-vapor`**: Vapor lacks a file logger for now, and this one doesn't have any dependencies.

Added SimpleFileLogger entry

---

README.md

- **Project Name**:
CrudRoute
- **Project URL**:
https://github.com/twof/VaporCRUDRouter
- **Project Description**:
Automatic RESTful CRUD router generation for any Fluent Model
It's a useful library for nearly any Vapor project

Add CrudRouter

---

README.md

- **Project Name**: Sublimate
- **Project URL**: https://github.com/gabrielepalma/sublimate
- **Project Description**: Fast prototyping with synchronization and authentication based on Sourcery

Added Sublimate

---

README.md

- **Project Name**: serversideswift
- **Project URL**: https://github.com/SwiftServerConf/serversideswift
- **Project Description**: The website for our ServerSide.swift conference
- **Why it should be added to `awesome-vapor`**: The website is built with vapor 😊

Added resources and project

---

README.md

- **Project Name**: Vapor – Deep Dive into Setup and Deployment for Heroku and Ubuntu
- **Project URL**: https://learningswift.brightdigit.com/vapor-heroku-ubuntu-setup-deploy/
- **Project Description**: Article describes the process of getting setup, converting to PostgreSQL, deploying to Heroku as well as an Ubuntu server
- **Why it should be added to `awesome-vapor`**: Great for beginners looking to get up and running

Added my tutorial on getting started and deployment

---

README.md

- Project Name: SwifQL
- Project URL: https://github.com/MihaelIsaev/SwifQL
- Project Description: Easily build flexible and type-safe SQL with pure Swift.
- Why it should be added to awesome-vapor: Looks like already quite mature and useful project that immediately gained a lot of traction.

Added SwifQL entry

---

README.md

Apparently I can’t do alphabet.

Reordered entries

---

README.md

- **Project Name**:
- **Project URL**:
- **Project Description**:

Updated Leaf Error Middleware to Vapor 3

---

README.md

- **Project Name**: Blog post
- **Project URL**: https://mikemikina.com/blog/watermarking-photos-with-imagemagick-vapor-3-and-swift-on-macos-and-linux/
- **Project Description**: Watermarking photos with ImageMagick, Vapor 3 and Swift on macOS and Linux
- **Why it should be added to `awesome-vapor`**: It is a tutorial on how to use the ImageMagick library in Vapor 3 and Swift.

Watermarking photos with ImageMagick, Vapor 3 and Swift on macOS and Linux

---

README.md

- **Project Name**: Blog post
- **Project URL**: https://mikemikina.com/blog/how-to-test-controllers-by-mocking-dependencies-in-vapor-3-and-swift/
- **Project Description**: How to test controllers by mocking dependencies in Vapor 3 and Swift
- **Why it should be added to `awesome-vapor`**: Article describing how to test controllers by mocking dependencies in Vapor 3 and Swift.

How to test controllers by mocking dependencies in Vapor 3 and Swift

---

README.md

- **CouchDB Client**:
- **https://github.com/makoni/couchdb-vapor**:
- **This is simple lib to work with CouchDB with Vapor 3.**:
- **Might be useful for developers using CouchDB. Also might be as an example for making HTTP requests in Vapor 3**:

CouchDB Client for Vapor added

---

README.md

- **Project Name**: Using the dependency injection framework for testing in Vapor 3 and Swift
- **Project URL**: https://mikemikina.com/blog/using-the-dependency-injection-framework-for-testing-in-vapor-3-and-swift/
- **Project Description**: Using the dependency injection framework for testing in Vapor 3 and Swift
- **Why it should be added to `awesome-vapor`**: Tutorial describing how to use dependency injection framework which will help you manage dependencies and mock them inside your tests.

Added blog post article: Using the dependency injection framework for testing in Vapor 3 and Swift.

---

README.md

- **Project Name**: Swifttube
- **Project URL**: http://www.swifttube.co
- **Project Description**: curates iOS conference videos in one place.
- **Why it should be added to `awesome-vapor`**: Built with Server Side Swift Vapor Framework

Added Swifttube

---

README.md

This is a service built by the Vapor team, similar to Vapor Cloud.

Add Vapor RED to services

---

Gemfile.lock

- **Project Name**:
- **Project URL**:
- **Project Description**:

Possibly fix CI
